### ISSUE TITLE
------------

### ISSUE THREAD

**Issue by rushikeshwalvekar** [AmitXShukla/GraphQL-Middleware-JWTAUTH-Authorization#12]

**Comment by AmitXShukla** [comment]
This is really old version, I see Angular CLI 6.
I’ll update this repo to latest Angular 9.1 next week. Stay tuned.

**Comment by rushikeshwalvekar** [comment]
thank you.

**Comment by rushikeshwalvekar** [comment]
sir any new update?

**Comment by AmitXShukla** [comment]
Hi rushikeshwalvekar, Sorry to keep you waiting, I tried to upgrade this repo, but couldn't make it work, there are too many issues. upgrading Angular 6 to 9 is easy, but GraphQL is not working properly yet. I will defer this repo until next Graph QL library update.
Once again, I'm sorry, I couldn't be of much help to you with this repository.
I will bring this GitHub repository offline.

- Amit
